### PR TITLE
Stem and create forms of very irregular German verbs

### LINKED ISSUE #163: Add irregular verb forms to German morphology exception check
We should make sure that German verbs with irregular conjugation patterns are treated as exceptions to produce the correct forms.

Associated PRs:
https://github.com/Yoast/javascript/pull/210
https://github.com/Yoast/YoastSEO.js-premium-configuration/pull/34

### PR DESCRIPTION
**Pull request by agnieszkaszuba**
## Summary
* [Non-user-facing] Improves keyphrase recognition for additional irregular verbs in German (e.g., `brennen`, `senden`, `kennen`).
* [Non-user-facing] Adds functionality to properly stem and create forms of very irregular verbs.

## Test instructions
This PR can be tested by following these steps:
User-facing:
* Set your site to German and make a new post with 150+ words.
* In the keyphrase, add a form of one of the following verbs: `brennen`, `bringen`,
`kennen`, `nennen`, `rennen`, `senden`, `wenden`, `werden`.
* In the text, add other forms of the same word. You can use a dictionary to find forms, e.g. https://de.wiktionary.org/wiki/Flexion:nennen.

Non-user-facing:
* Make sure the correct word forms are created for the following verbs (via unit tests): _sein_, _haben_, _tun_
* Make sure each form of the above verbs stems to its infinitive form (so _sein_, _haben_, and _tun_) (via unit tests).

Fixes #163

### CODE REVIEW

**Comment by manuelaugustin** [comment]
CR done 👍

When acceptance testing, it would be great if you could also have a quick CR-look at  the last commits I added.

File: packages/yoastseo/spec/morphology/german/generateVerbExceptionFormsSpec.js [hunk 1]
```diff
@@ -210,6 +210,160 @@ describe( "Test for generating verb exceptions in German", () => {
...
+	} );
+
+	it( "creates forms for the verb 'werden', same result with past subjunctive stem", () => {
+		expect( generateVerbExceptionForms( morphologyDataDE.verbs, "würd" ) ).toEqual(
+			generateVerbExceptionForms( morphologyDataDE.verbs, "werd" ) );
+	} );
+
+	it( "creates forms for the verb 'werden', same result with past participle stem", () => {
+		expect( generateVerbExceptionForms( morphologyDataDE.verbs, "word" ) ).toEqual(
+			generateVerbExceptionForms( morphologyDataDE.verbs, "word" ) );
```
Comment (nataliashitova) [inline packages/yoastseo/spec/morphology/german/generateVerbExceptionFormsSpec.js]: This looks a little trivial (and likely resulted from a copy-paste accident) 😄

File: packages/yoastseo/spec/morphology/german/generateVerbExceptionFormsSpec.js [hunk 2]
```diff
@@ -210,6 +210,160 @@ describe( "Test for generating verb exceptions in German", () => {
...
+			"brachtet",
+			"brächte",
+			"brächten",
+			"brächtest",
+			"brächtet",
+			"gebracht",
+		] );
+	} );
+
+	it( "creates forms for an irregular verb, same result with past stem", () => {
```
Comment (nataliashitova) [inline packages/yoastseo/spec/morphology/german/generateVerbExceptionFormsSpec.js]: For this and all following similar tests, wouldn't it be more clear to define an entire paradigm and test (in a loop) that all other forms get generated for each and every one of them?

File: packages/yoastseo/src/morphology/german/generateVerbExceptionForms.js [hunk 3]
```diff
@@ -93,6 +103,26 @@ const generateFormsStrongVerbs = function( morphologyDataVerbs, stemmedWordToChe
...
+	if ( matchedParadigm ) {
+		return matchedParadigm.forms;
+	}
+
+	return [];
+};
+
+
 /**
  * Checks whether a give stem stem falls into any of the verb exception categories and creates the
```
Comment (nataliashitova) [inline packages/yoastseo/src/morphology/german/generateVerbExceptionForms.js]:
```suggestion
 * Checks whether a given stem falls into any of the verb exception categories and creates the
```

File: packages/yoastseo/src/morphology/german/getForms.js [hunk 4]
```diff
@@ -107,7 +107,7 @@ const addFormsWithRemovedLetters = function( morphologyDataNouns, stemmedWordToC
  * @returns {Array<string>} The created word forms.
  */
 export function getForms( word, morphologyData ) {
-	const stemmedWord = stem( word );
+	const stemmedWord = stem( morphologyData.verbs, word );
```
Comment (nataliashitova) [inline packages/yoastseo/src/morphology/german/getForms.js]: I think it would be a bit more consistent if the `morphologyData` argument would follow the `word`. This is how we've done it so far (including in this exact function), and it also helps reading: `do_something to A using B`, not `do_something using B to A`.

**Comment by nataliashitova** [comment]
I've noticed a few minor problems in the code. @manuelaugustin Could you take a look?

File: packages/yoastseo/src/morphology/german/getForms.js (hunk 4 above)
Comment (nataliashitova) [reply packages/yoastseo/src/morphology/german/getForms.js]: In consultation with @manuelaugustin we've decided that although it's a valid point, it falls somewhat outside the scope of this PR. It will be addressed separately, during clean-up of the German morphology phase.

**Comment by manuelaugustin** [comment]
CR & acceptance 👍

During testing I noticed an incorrectly named data import, which is fixed now.
