### PR TITLE
Fixed styling select components

### LINKED ISSUE #601: Fix styling Select component
parent: https://github.com/Yoast/javascript/issues/560.

The Styling looks a bit off, for example the colour of the multiselect is white instead of yoast-purple.
Screenshot 2020-04-06 at 14 17 28

### PR DESCRIPTION
**Pull request by rolf-yoast**
## Summary

This PR can be summarized in the following changelog entry:

* Changed css for select components
* Added argument to select2 to make full width

## Relevant technical choices:

*

## Test instructions

This PR can be tested by following these steps:

* Checkout 14433-reactify-advanced-settings-tab from wordpress-seo
* Checkout 601-styling-select-component from javascript
* Link monorepo from wordpress-seo
* Check if select components are working and look good in a post under the "Advanced" tab in Yoast SEO
* In terminal go to the javascript repo.
* Go to directory app/components
* Run "yarn install & yarn start"
* Browse to http://0.0.0.0:3333/
* Click on "Reactified components" in the top and check if elements are working correctly and look good on the page

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  *

## UI changes
* [x] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes #601 and https://github.com/Yoast/wordpress-seo/issues/14726

### CODE REVIEW

**Comment by JoseeWouters** [comment]
CR 👍 

Acceptance 🚧 

The options in the select2 are a bit too far down, the option in the normal select a bit too far up. Maybe we need different css rules for this. 
afbeelding

**Comment by JoseeWouters** [comment]
CR + Acceptance 👍 

But Travis fails, could you look into that?

File: packages/components/src/select/Select.js [hunk 1]
```diff
@@ -71,7 +71,7 @@ class MultiSelect extends React.Component {
 	 */
 	componentDidMount() {
 		this.select2 = jQuery( `#${ this.props.id }` );
-		this.select2.select2();
+		this.select2.select2({ width: '100%' });
```
Comment (JoseeWouters) [inline packages/components/src/select/Select.js:74]: This should fix the Travis build
```suggestion
		this.select2.select2( { width: "100%" } );
```
