### PR TITLE
457 determine unique stem

### LINKED ISSUE #457: Determine a unique stem for Dutch word
## Explanation

A function that will give us one unique stem of Dutch words, especially the words that are listed in the exception list which have more than one stems. 
This functionality will be used for internal linking.

### PR DESCRIPTION
**Pull request by FAMarfuaty**
## Summary

This PR can be summarized in the following changelog entry:

* [yoastseo] Adds the master function for Dutch stemming.

## Relevant technical choices

*  It calls other smaller functions such as smaller stemmer function, participle stemmer, words ending in t/d stemmer.

## Test instructions

This PR can be tested by following these steps:

* Add more words to the specs
* Run `yarn test` and make sure there is no failing test

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [x] I have added unittests to verify the code works as intended

Fixes #457

### CODE REVIEW

File: packages/yoastseo/spec/morphology/dutch/determineStemSpec.js [hunk 1]
```diff
@@ -0,0 +1,349 @@
+import { determineStem } from "../../../src/morphology/dutch/determineStem";
+import getMorphologyData from "../../specHelpers/getMorphologyData";
+
+
+const morphologyDataNL = getMorphologyData( "nl" ).nl;
+
+/*
```
Comment (nataliashitova) [inline packages/yoastseo/spec/morphology/dutch/determineStemSpec.js]:
```suggestion
/**
```

File: packages/yoastseo/src/morphology/dutch/determineStem.js [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+	const doNotStemPrefixException = doNotStemPrefix.find( exception => stemmedWord.endsWith( exception ) );
+	let stemmedWordWithoutPrefix = "";
+
+	// Check whether the stemmedWord is in the list of strong verbs starting with be-, ont- or ver- that do not need to be stemmed.
+	if ( doNotStemPrefixException ) {
+		foundPrefix = null;
+		// If the inputted stem is started with one of the separable compound prefixes, the prefix needs to be deleted for now.
+	} else if ( foundPrefix ) {
+		stemmedWordWithoutPrefix = stemmedWord.slice( foundPrefix.length, stemmedWord.length );
+		// At least 3 characters so that e.g. "be" is not found in the stem "berg".
```
Comment (nataliashitova) [inline packages/yoastseo/src/morphology/dutch/determineStem.js]: I think that determining prefix correctly and only in words where it can actually be a prefix should be a task of the function that checks the prefix in the word (line 38 in the current version).

File: packages/yoastseo/src/morphology/dutch/determineStem.js [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+		if ( stemmedWordWithoutPrefix.length > 2 ) {
+			stemmedWord = stemmedWordWithoutPrefix;
+		} else {
+			// Reset foundPrefix so that it won't be attached when forms are generated.
```
Comment (nataliashitova) [inline packages/yoastseo/src/morphology/dutch/determineStem.js]: Can you be more specific? Which forms are generated?

File: packages/yoastseo/spec/morphology/dutch/stemTOrDFromEndOfWordSpec.js [hunk 4]
```diff
@@ -0,0 +1,13 @@
+import { stemTOrDFromEndOfWord } from "../../../src/morphology/dutch/stemTOrDFromEndOfWord";
+import getMorphologyData from "../../specHelpers/getMorphologyData";
+
+const morphologyDataNL = getMorphologyData( "nl" ).nl;
+
+describe( "Creates forms form stem from words with ambiguous endings", () => {
```
[the remark this answers is not in the document]
Comment (FAMarfuaty) [reply packages/yoastseo/spec/morphology/dutch/stemTOrDFromEndOfWordSpec.js]: All of the cases above are already covered in the determine spec
